### ISSUE TITLE
Update docs workflow to use reusable workflow

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#139]
### Purpose

A reusable workflow has been developed in the sailbot workspace. The workflow in this repository should be updated to use the reusable workflow to eliminate duplicate code in multiple repositories.

### Changes

- Add a `test.yml` to the workflows folder similar to what [network systems has](https://github.com/UBCSailbot/network_systems/blob/main/.github/workflows/tests.yml)
- Add the hyperlink redirection linter as a job to the [sailbot workspace reusable workflow file](https://github.com/UBCSailbot/sailbot_workspace/blob/main/.github/workflows/test_definitions.yml)
- Remove the old workflow files from the docs repo
- **Remember to enable the rebuild docs job and disable irrelevant jobs like colcon-test for example**

**Comment by patrick-5546** [comment]
Completed in #142
