### ISSUE TITLE
Update docs pages Sailbot Workspace/Setup and Sailbot Workspace/Workflow

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#162]
### Purpose

Recent changes to the launch structure of our codebase prompt us to change our setup and workflow instructions to include launch debugging instructions.

### Changes

We want to add the following to both pages:
- Launch instructions, both for specific packages and globally
- Debugging, both for specific packages and globally

**Comment by DFriend01** [comment]
@patrick-5546 Creating this issue in response to [this comment](https://github.com/UBCSailbot/sailbot_workspace/pull/154#issuecomment-1699689520)

**Comment by patrick-5546** [comment]
For debugging, we can talk about
- Debug configurations
- Unit tests (C++ support added in https://github.com/UBCSailbot/sailbot_workspace/pull/58)
    <img width="312" alt="image" src="https://github.com/UBCSailbot/docs/assets/65756895/d2a0efc9-fddc-4398-ad1f-1603adc7505a">
