### ISSUE TITLE
Adding Configuration File for Hyperlink Linter

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#88]
### Purpose
We want to allow the end-user to specify what patterns or files they want to ignore during the linting process. To this end, we will add the support for a configuration file (a `.json` file) to allow for ignoring patterns and files.

### Changes
1. Modify the linter to read the config file (if it exists) and ignore the specified files and patterns. The linter should not consider anything in the config file. Ignore patterns should be python-flavored regex and ignore files should be specified as a path to the file relative to the project root directory.
2. Add a config file argument in the [`lint.yml`](https://github.com/UBCSailbot/docs/blob/main/.github/workflows/lint.yml) file to specify the path to the config file relative to the root of the project.
3. The config file should have the following syntax:

```json
{
   "ignoreFiles": [
      {
         "file": "./path/to/file.md"
      },
      {
         "file": "..."
      }
   ],

   "ignorePatterns": [
      {
         "pattern": "pattern1?\".*\""
      },
      {
         "pattern": "..."
      }
   ]
}
```

**Note:** Consider what might happen when `\"` needs to be read as a raw string. However, this bug might be unavoidable.

### Resources
- https://github.com/UBCSailbot/docs/issues/70
- https://github.com/UBCSailbot/docs/pull/86
- [Workflow Arguments](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) -- Access arguments from workflow config file in the environment variables.

**Comment by patrick-5546** [comment]
Another option would be to define configurations in the workflow file
https://github.com/UBCSailbot/docs/blob/fe56aa3b940bddfb6f9d36ae789664494e374e4d/.github/workflows/lint.yml#L20-L21

**Comment by patrick-5546** [comment]
For ignore files, try to follow unix CLI conventions and find Python function that does this (potentially os or pathlib). Ignore patterns might be better in the config file and use regex
